
services:
  backend:
    build: ./backend
    container_name: backend-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_OAUTH2_CLIENT_ID=380150573582-kb1o6joft18fn0mqld0g0m9snkb2hvph.apps.googleusercontent.com
      - SPRING_OAUTH2_CLIENT_SECRET=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
    networks:
      - app-network
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend-container
    networks:
      - app-network
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"  # Exposing Nginx on port 80
      - "443:443"  # Exposing Nginx for HTTPS
    depends_on:
      - backend  # Ensure backend starts before Nginx
      - frontend  # Ensure frontend starts before Nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Allows containers to communicate within the same network